version: "3.3"
networks:
  gamutrf:
services:
  geolocate:
    restart: always
    image: iqtlabs/birdseye:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - gamutrf
    ports:
      - '4999:4999'
    environment:
      - 'ORCHESTRATOR=${ORCHESTRATOR}'