[Methods]
# particle filter initialization larger r  
# adjust dqn env observation heatmap size 
env : RFMultiEnv
method : mcts
action : simpleactions
sensor : doublerssi
state : rfmultistate 
target_speed: 1.0
target_start: 100
resample_proportion: 0.005
fading_sigma: 4.0
reward: range_reward
#reward: entropy_collision_reward
#target_speed_range: [0,1,2,3,4]

[Defaults]
lambda_arg : 0.8
collision : -2.
loss : -2.
depth : 10
simulations : 200
plotting : False
trials : 500
iterations : 150
