[Methods]
# particle filter initialization larger r  
# adjust dqn env observation heatmap size 
env : RFMultiEnv
method : mcts
action : simpleactions
sensor : doublerssi
#sensor : singlerssi
state : rfmultistate 
antenna_filename: radiation_pattern_yagi_5.csv
#antenna_filename: radiation_pattern_monopole.csv
n_targets: 2
target_speed: 1.0
target_start: 130
#resample_proportion: 0.005
fading_sigma: 8.0
particle_resample: 0.01
particle_min: 10
particle_max: 200
#reward: range_reward
reward: heuristic_reward
#reward: entropy_collision_reward
version: paper
delta_col: 15
#likelihood: weight2
#target_speed_range: [0,1,2,3,4]

[Defaults]
lambda_arg : 0.8
collision : -2.
loss : -2.
depth : 10
simulations : 100
#200
plotting : False
trials : 500
iterations : 150
