[Methods]
# particle filter initialization larger r  
# adjust dqn env observation heatmap size 
env : RFMultiEnv
method : baseline
action : baselineactions
sensor : doublerssi
state : rfmultistate 
target_speed: 1.0
target_start: 100
#resample_proportion: 0.005
fading_sigma: 0.0
#reward: range_reward
particle_resample: 0.01
particle_min: 10
particle_max: 200
#reward: range_reward
#target_speed_range: [0,1,2,3,4]

[Defaults]
policy : random
plotting : True
trials : 500
timesteps : 150
