name: test buildx

on: [push, pull_request]

jobs:
  buildx-birdeye:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push platforms
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: iqtlabs/birdseye:${{ steps.change_version.outputs.VERSION }}
