name: Code health checks

on: [push, pull_request]

env:
  CODECHECK_PY_VER: 3.9

jobs:
  codecheck:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up python-${{ env.CODECHECK_PY_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.CODECHECK_PY_VER }}
      - name: Run code checks
        run: |
          pip3 install -r requirements.txt -r tests/requirements.txt && \
          export PYTHONPATH=$PWD/birdseye:$PYTHONPATH && \
          pylint --fail-under=7.5 *py tests/*py birdseye/*py && \
          pytype -k -P . -V ${{ env.CODECHECK_PY_VER }} birdseye/*py *py telemetry-data/*/*py
