name: Code health checks

on: [push, pull_request]

env:
  CODECHECK_PY_VER: 3.9

jobs:
  codecheck:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up python-${{ env.CODECHECK_PY_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.CODECHECK_PY_VER }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          version: 1.4.2
      - name: poetry install
        run: |
          poetry build && poetry install --extras=dev --no-root
      - name: Run code checks
        run: |
          export PYTHONPATH=$PWD/birdseye:$PYTHONPATH && \
          pylint --fail-under=7.5 *py tests/*py birdseye/*py && \
          pytype -k -P . -V ${{ env.CODECHECK_PY_VER }} birdseye/*py *py telemetry-data/*/*py
